services:
  app-legacy:
    image: nginx:1.25.2
    volumes:
      - "./app-legacy/src:/usr/share/nginx/html"
      - "./app-legacy/nginx/app-local.conf:/etc/nginx/conf.d/app-local.conf"

  app-new:
    build:
      context: app-new
      dockerfile: Dockerfile

  proxy:
    image: nginx:1.25.2
    ports:
      - "9000:80"
    volumes:
      - "./nginx/app.conf:/etc/nginx/conf.d/app.conf"
