version: '3.8'

services:
  app-legacy:
    image: nginx:1.25.2
    ports:
      - "2000:80"
    volumes:
      - "./app-legacy/src:/usr/share/nginx/html"
      - "./app-legacy/nginx/app-local.conf:/etc/nginx/conf.d/app-local.conf"

  app-new:
    build:
      context: app-new
      dockerfile: Dockerfile
    ports:
      - "2001:3000"
